#!/usr/bin/python
import os

print("Content-type: text/html\r\n\r\n")
# print("<font size=+1>Environment</font><\br>");
for param in os.environ.keys():
   print("%30s: %s" % (param, os.environ[param]))



# CONTENT_TYPE

# The data type of the content. Used when the client is sending attached content to the server. For example, file upload.
# 2 	

# CONTENT_LENGTH

# The length of the query information. It is available only for POST requests.
# 3 	

# HTTP_COOKIE

# Returns the set cookies in the form of key & value pair.
# 4 	

# HTTP_USER_AGENT

# The User-Agent request-header field contains information about the user agent originating the request. It is name of the web browser.
# 5 	

# PATH_INFO

# The path for the CGI script.
# 6 	

# QUERY_STRING

# The URL-encoded information that is sent with GET method request.
# 7 	

# REMOTE_ADDR

# The IP address of the remote host making the request. This is useful logging or for authentication.
# 8 	

# REMOTE_HOST

# The fully qualified name of the host making the request. If this information is not available, then REMOTE_ADDR can be used to get IR address.
# 9 	

# REQUEST_METHOD

# The method used to make the request. The most common methods are GET and POST.
# 10 	

# SCRIPT_FILENAME

# The full path to the CGI script.
# 11 	

# SCRIPT_NAME

# The name of the CGI script.
# 12 	

# SERVER_NAME

# The server's hostname or IP Address
# 13 	

# SERVER_SOFTWARE

