servers: # liste de serveurs
  - server: # un serveur
      server_name: domain1.com # nom du serveur (optionnel)
      port: 8080 # port du serveur (optionnel, default: 80)
      error_pages: # liste des pages d'erreur par defaut (optionnel)
        - 404: PWD/www/errors/404.html
      client_max_body_size: 2k # taille max des requetes en megaoctets (optionnel, default: 2k)
      routes: # liste des routes du serveur (optionnel ?)
        - /:
            methods: GET # methodes autorisees par la route (optionnel, default: GET)
            root: PWD/www/ # racine de la route (optionnel, default: PWD/www/ + url)
            repertory_listing: false # autorise le listing des repertoires (optionnel, default: false)
            index: index.html # page index (optionnel, default: index.html)
        - /google/:
            redirection: www.google.com # redirection de la route (optionnel)
        - /new_user/:
            cgi: .py PWD/cgi/python_cgi # cgi 'extension' 'racine du cgi' (optionnel)
            methods: POST
            redirection: /404.html # redirection de la route (optionnel)
        - /php_cgi/:
            cgi: .php /usr/bin/php
            methods: GET
        - /uploader/:
            methods: POST
            upload: PWD/www/files/ # racine du telechargement, active l'upload de fichier (optionnel)
        - /admin/:
            methods: GET
            root: PWD/www/admin
            repertory_listing: true
  - server:
      server_name: domain2.com
      port: 8060
      routes:
        - /:
            methods: GET
            root: PWD/www/
            index: index.html
