servers:
  - server:
      server_name: domain1.com
      port: 8080
      error_pages:
        - 404: ./404.html
      client_max_body_size: 100m
      routes:
        - /:
            methods: GET
            root: PWD/www/
            index: index.html 
        - /post_body/:
            methods: POST
            root: PWD/www/
        - /put_test/:
            methods: POST PUT
            root: PWD/www/
        - /directory/:
            methods: GET
            root: PWD/www/YoupiBanane/
            index: youpi.bad_extension
